(in-package #:org.numbra.cl-tikz-tilings)

(defparameter *three-chessboard*
  (defhomshift three-chessboard ()
    (:blue :red)
    (:blue :green)
    (:green :red)))

(defparameter *house*
  (defhomshift house ()
    (:blue :red)
    (:blue :green)
    (:green :red)
    (:red :purple)
    (:purple :yellow)
    (:yellow :green)))

(defparameter *golden-mean*
  (defhomshift golden-mean ()
    (:white :black)
    (:white :white)))

(defparameter *ken-katabami-loop*
  (defhomshift ken-katabami-loop
      ((:blue :a1)
       (:red :a2)
       (:white . t))
    (:a1 :a1p)
    (:a1 :b1)
    (:a1p :b1-)
    (:a1p :f1+)
    (:b1 :c1)
    (:b1 :b1-)
    (:b1 :b1+)
    (:c1 :c1p)
    (:c1 :d1)
    (:c1p :d1-)
    (:c1p :b1+)
    (:d1 :e1)
    (:d1 :d1-)
    (:d1 :d1+)
    (:e1 :e1p)
    (:e1 :f1)
    (:e1p :f1-)
    (:e1p :d1+)
    (:f1 :a1)
    (:f1 :f1-)
    (:f1 :f1+)
    (:x1 :b1-)
    (:x1 :b1+)
    (:x1 :d1-)
    (:x1 :d1+)
    (:x1 :f1-)
    (:x1 :f1+)
    ;; Connect the two parts of the graph
    (:a1 :a2)
    ;; Same as above, with 1 -> 2
    (:a2 :a2p)
    (:a2 :b2)
    (:a2p :b2-)
    (:a2p :f2+)
    (:b2 :c2)
    (:b2 :b2-)
    (:b2 :b2+)
    (:c2 :c2p)
    (:c2 :d2)
    (:c2p :d2-)
    (:c2p :b2+)
    (:d2 :e2)
    (:d2 :d2-)
    (:d2 :d2+)
    (:e2 :e2p)
    (:e2 :f2)
    (:e2p :f2-)
    (:e2p :d2+)
    (:f2 :a2)
    (:f2 :f2-)
    (:f2 :f2+)
    (:x2 :b2-)
    (:x2 :b2+)
    (:x2 :d2-)
    (:x2 :d2+)
    (:x2 :f2-)
    (:x2 :f2+)))
